### ISSUE TITLE
i hope to know the relationship of the joint name in urdf & ros2 control label & controller config file?

### ISSUE THREAD

**Issue by PANJIACHENG-98** [ros-controls/ros2_control#1539]
1. urdf only shows one joint J1. 
```
  <joint
    name="J1"
    type="revolute">
    <!-- <origin
      xyz="0 0 0"
      rpy="0 0 0" /> -->
    <origin
      xyz="0 0 0.2605"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link-J1" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-3.0543"
      upper="3.0543"
      effort="0"
      velocity="0" />
  </joint>
```

2. ros2 control label : 
```
    <ros2_control name="H1_robot_ros2_control" type="system">
      <hardware>
          <plugin>hyy_hardware_interface/HyyHardwareInterface</plugin>
      </hardware>
      
      <xacro:macro name ="joint_interface" params="Joint_Name initial_pos initial_vel initial_effort">
        <joint name="${Joint_Name}">
            <command_interface name="position"/>
            <command_interface name="velocity"/>
            <command_interface name="effort"/>
            <state_interface name="position">
                <param name="initial_value">${initial_pos}</param>
            </state_interface>
            <state_interface name="velocity">
                <param name="initial_value">${initial_vel}</param>
            </state_interface>
            <state_interface name="effort">
                <param name="initial_value">${initial_effort}</param>
            </state_interface>
        </joint>
      </xacro:macro>

    <xacro:joint_interface Joint_Name="L-J1" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J2" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J3" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J4" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J5" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J6" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="L-J7" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J1" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J2" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J3" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J4" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J5" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J6" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="R-J7" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="J1" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="Body" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="H-J1" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>
    <xacro:joint_interface Joint_Name="H-J2" initial_pos="0.0" initial_vel="0.0" initial_effort="0.0"/>

    </ros2_control>
```

3. controller config file :

```
controller_manager:
  ros__parameters:
    update_rate: 1000  

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    default_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    hyy_left_arm_controller:
      type: hyy_controller/HyyController
    hyy_right_arm_controller:
      type: hyy_controller/HyyController
    hyy_body_controller:
      type: hyy_controller/HyyController
    hyy_head_controller:
      type: hyy_controller/HyyController
    hyy_external_device_controller:
      type: hyy_external_controller/HyyExternalController

default_left_arm_controller:
  ros__parameters:
    joints: 
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

hyy_left_arm_controller:
  ros__parameters:
    joints: 
      - L-J1
      - L-J2
      - L-J3
      - L-J4
      - L-J5
      - L-J6
      - L-J7

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    component_index: 0

hyy_right_arm_controller:
  ros__parameters:
    joints: 
      - R-J1
      - R-J2
      - R-J3
      - R-J4
      - R-J5
      - R-J6
      - R-J7

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    component_index: 1

hyy_body_controller:
  ros__parameters:
    joints: 
      - J1
      - Body

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    component_index: 0
    if_additionaxis: 1

hyy_head_controller:
  ros__parameters:
    joints: 
      - H-J1
      - H-J2

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    component_index: 1
    if_additionaxis: 1
```

I think that if the joint name in the ros2_control tag corresponds to the controller config, it can ensure that the controller transmits correct data to the hardware layer using the correct command interface. The joint name in the ros2_control tag corresponds to the joint name in urdf, which can ensure that the joint status broadcaster controller can publish the correct joint status, corresponding to the joint name in TF, so that rviz displays normally。

Am i Right? Give my some advise?
