### ISSUE TITLE
`rw_rate` with multiple hardware components leads to skipped cycles

### ISSUE THREAD

**Issue by RobertWilbrandt** [ros-controls/ros2_control#2089]
**Describe the bug**
We currently have a robot system with two hardware components (a UR16e and a kuka KR50), one running at 500Hz and one running at 250Hz. The controller manager `update_rate` is set to 500 and the slower interface uses the `rw_rate` attribute:
```
<ros2_control name="${name}" type="system" rw_rate="250">
  [...]
</ros2_control>
```

With this setup, the slower hardware is not able to move smoothly and "stutters". Using the tracing in [kuka_rsi_driver](https://github.com/fzi-forschungszentrum-informatik/kuka_rsi_driver), we can clearly see that the read- and write-functions frequently "miss a step" (see screenshots), i.e. only get called after 3 cycles instead of every 2.

**Expected behavior**
The `read()` and `write()` functions of the slower hardware interface should get called in every other control cycle consistently.

**Screenshots**

Through tracing we obtained the periods between successive `read()` and `write()` calls in our hardware interface. We expect these functions to be called every ~4ms, but we can clearly see that the period often times jumps to ~6ms:
![Image](https://github.com/user-attachments/assets/93e26dcd-2f72-4c9e-b2a1-8e730da6a608)

In detail:
![Image](https://github.com/user-attachments/assets/7ae812dd-5eea-4b96-8870-ed4ca87bd0b1)

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
- Version: Jazzy
- ros2_control is built from sources

**Additional context**
It seems like the [calculation in resource_manager](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/src/resource_manager.cpp#L1788) is the cause of the problem. It currently only ensures that the read/write functions are not called too frequently by checking
`actual_period.seconds() * read_rate >= 0.99`

I suspect that jitter in the faster hardware interface execution time leads to this deciding to skip a cycle frequently. I think a better approach would be to also consider the "timing error" resulting from skipping the call in a given cycle:
`(actual_period.seconds() + 1. / resource_storage_->cm_update_rate_) * read_rate`

I am going to check if this fixes the problem for our setup and try creating a PR if successful.

**Comment by saikishor** [comment]
@RobertWilbrandt Do you mind giving a shot the PR #2086 and share the diagnostics of your HW components?

Thank you

**Comment by RobertWilbrandt** [comment]
Sure, i could not yet run this again on real hardware but the problem persists with two mock components. Here are the diagnostics i obtained:

![Image](https://github.com/user-attachments/assets/079094c4-e2f5-496d-bc70-7789b3517687)

```
header:
  stamp:
    sec: 1741023996
    nanosec: 514931812
  frame_id: ''
status:
- level: "\0"
  name: 'controller_manager: Controllers Activity'
  message: Not all controllers are active
  hardware_id: ros2_control
  values:
  - key: schunk_ppd_controller.state
    value: inactive
  - key: joint_trajectory_controller.state
    value: active
  - key: joint_trajectory_controller.execution_time
    value: 'Avg: 7.79 [2.13 - 799.52] us, StdDev: 6.21'
  - key: kuka_status_broadcaster.state
    value: active
  - key: kuka_status_broadcaster.execution_time
    value: 'Avg: 2.13 [0.73 - 826.37] us, StdDev: 3.27'
  - key: kuka_pose_broadcaster.state
    value: active
  - key: kuka_pose_broadcaster.execution_time
    value: 'Avg: 2.66 [0.92 - 117.01] us, StdDev: 2.32'
  - key: kuka_joint_trajectory_controller.state
    value: inactive
  - key: joint_state_broadcaster.state
    value: active
  - key: joint_state_broadcaster.execution_time
    value: 'Avg: 42.85 [13.24 - 591.20] us, StdDev: 24.28'
  - key: ur_joint_trajectory_controller.state
    value: inactive
- level: "\x02"
  name: 'controller_manager: Hardware Components Activity'
  message: '

    High periodicity jitter or mean error : [ kuka_kr50 ]'
  hardware_id: ros2_control
  values:
  - key: ur.state
    value: active
  - key: ur.read_cycle.execution_time
    value: 'Avg: 12.12 [2.04 - 629.76] us, StdDev: 13.27'
  - key: ur.write_cycle.execution_time
    value: 'Avg: 17.22 [0.02 - 217.41] us, StdDev: 13.32'
  - key: kuka_kr50.state
    value: active
  - key: kuka_kr50.read_cycle.execution_time
    value: 'Avg: 2.25 [0.26 - 57.75] us, StdDev: 1.87'
  - key: kuka_kr50.read_cycle.periodicity
    value: 'Avg: 249.40 [157.75 - 252.52] Hz, StdDev: 6.82 -> Desired : 250 Hz'
  - key: kuka_kr50.write_cycle.execution_time
    value: 'Avg: 3.64 [0.54 - 94.76] us, StdDev: 3.84'
  - key: kuka_kr50.write_cycle.periodicity
    value: 'Avg: 230.24 [148.74 - 252.53] Hz, StdDev: 34.11 -> Desired : 250 Hz'
- level: "\x02"
  name: 'controller_manager: Controller Manager Activity'
  message: 'Controller Manager has bad periodicity : 500.302890 Hz. Expected consistent 500 Hz'
  hardware_id: ros2_control
  values:
  - key: update_rate
    value: '500'
  - key: periodicity.average
    value: '500.302890'
  - key: periodicity.standard_deviation
    value: '86.005452'
  - key: periodicity.min
    value: '233.325128'
  - key: periodicity.max
    value: '34331.227685'
```

I guess the controller manager periodicity stems from me running this locally without RT or low-latency kernel, but the `kuka_kr50.[read|write]_cycle.periodicity ` seem to show the same problem i am observing: One cycle missed => 6ms period => 166Hz frequency recorded.
