### ISSUE TITLE
[ros2_control_node-1] [ERROR] [1742473810.665745003] [hand_controller]: Joint name cannot be empty

### ISSUE THREAD

**Issue by mynamelzy** [ros-controls/ros2_control#2119]
my  yaml is 
```yaml
controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    hand_controller:
      type: position_controllers/GripperActionController

hand_controller:
  ros__parameters:
    type: position_controllers/GripperActionController
    joints:
      - right_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interface_name: position
```

and  my hand.ros2_control.xacro
```xml
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="hand_ros2_control" params="name prefix">
    <ros2_control name="${name}" type="system">
      <hardware>
          <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>
          <param name="joint_commands_topic">/hand_joint_commands</param>
          <param name="joint_states_topic">/hand_joint_states</param>
      </hardware>
      <joint name="right_joint">
        <command_interface name="position"/>
        <state_interface name="position">
        <param name="initial_value">0.0</param>
        </state_interface>
      </joint>
    </ros2_control>
  </xacro:macro>

</robot>
```

my yaml has right_joint,but it shows me "Joint name cannot be empty",i dont know how to solove this question
