### ISSUE TITLE
Failed to start gripper controller and arm controller simultaneously

### ISSUE THREAD

**Issue by AndyZe** [ros-controls/ros2_control#487]
We are starting a gripper controller and an arm trajectory controller simultaneously. `controllers.yaml` given below. Starting controllers fails like so. To me, this seems like a parsing issue in the resource_manager?

```
[ros2_control_node-1] [ERROR] [1628170893.039272048] [resource_manager]: Component 'KortexMultiInterfaceHardware' did not accept new command resource combination: 
[ros2_control_node-1]  Start interfaces: 
[ros2_control_node-1] [
[ros2_control_node-1]   joint_1/position
[ros2_control_node-1]   joint_2/position
[ros2_control_node-1]   joint_3/position
[ros2_control_node-1]   joint_4/position
[ros2_control_node-1]   joint_5/position
[ros2_control_node-1]   joint_6/position
[ros2_control_node-1]   joint_7/position
[ros2_control_node-1] ]
[ros2_control_node-1] Stop interfaces: 
[ros2_control_node-1] [
[ros2_control_node-1] ]
[ros2_control_node-1] 
[ros2_control_node-1] [ERROR] [1628170893.039285684] [controller_manager]: Could not switch controllers since prepare command mode switch was rejected.
[ros2_control_node-1] [ERROR] [1628170893.039388955] [resource_manager]: Component 'KortexMultiInterfaceHardware' did not accept new command resource combination: 
[ros2_control_node-1]  Start interfaces: 
[ros2_control_node-1] [
[ros2_control_node-1]   finger_joint/position
[ros2_control_node-1] ]
[ros2_control_node-1] Stop interfaces: 
[ros2_control_node-1] [
[ros2_control_node-1] ]
[ros2_control_node-1] 
[ros2_control_node-1] [ERROR] [1628170893.039406176] [controller_manager]: Could not switch controllers since prepare command mode switch was rejected.
```

Controller yaml:
```
controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: forward_command_controller/ForwardCommandController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

hand_controller:
  ros__parameters:
    joints:
      - finger_joint
    interface_name: position
```
