### ISSUE TITLE
Servo not timing out: JointJog

### ISSUE THREAD

**Issue by brennand** [ros-controls/ros2_control#570]
**Describe the bug**

1) When I send a Joint Jog msg via a RVIZ Interactive marker.  The joint moves as expected.  It will stop moving when release the mouse button.  A ros2 topic echo looks like:

```
 ---
header:
  stamp:
    sec: 2221
    nanosec: 450000000
  frame_id: world
joint_names:
- elbow_joint
displacements: []
velocities:
- -1.0
duration: 0.0
---
```

When I create the same msg in python and publish.  Servo gets the msg and will move the joint but it doesn't time out.  This is the msg:

```
---
header:
  stamp:
    sec: 1635791353
    nanosec: 994980307
  frame_id: world
joint_names:
- elbow_joint
displacements: []
velocities:
- 1.0
duration: 0.0
---
```

This is the python code:

```
    def move_joint(self, data):
        joint_jog_msg = JointJog()
        joint_jog_msg.header.stamp = self.get_clock().now().to_msg()
        joint_jog_msg.header.frame_id = "world"
        joint_jog_msg.joint_names = [str(data["joint"])]
        joint_jog_msg.velocities = [float(data["direction"])]
        joint_jog_msg.duration = 0.0
        self.get_logger().info("move_joint: %s" % str(data["joint"]))
        self.move_joint_publisher_.publish(joint_jog_msg)
```

The only difference I can see if that the time stamps are different in the msgs.

The servo.yaml setting:

`incoming_command_timeout:  0.1`

You can also easily reproduce this by using command line:

ros2 topic pub /servo_server/delta_joint_cmds control_msgs/JointJog "{joint_names: ['elbow_joint'], displacements: [], velocities: [1.0], duration: 0.0}"

Change the topic + the joint.

**To Reproduce**
1. Run you robot that has servo 
2. Move the joint via RIVZ, this should move the joint you selected.
3. On the command line you can reproduce this by sending: 
`ros2 topic pub /servo_server/delta_joint_cmds control_msgs/JointJog "{joint_names: ['elbow_joint'], displacements: [], velocities: [1.0], duration: 0.0}"`
But change the joint name.
4. The joint should keep on rotating

**Expected behavior**
When you send a single Msg it should time out.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version Rolling
- Anything that may be unusual about your environment: No
