### ISSUE TITLE
Individual controller's update_rate is confusing

### ISSUE THREAD

**Issue by tonynajjar** [ros-controls/ros2_control#872]
Setting an individual controller update rate is confusing. I noticed, according to this [line](https://github.com/ros-controls/ros2_control/blob/master/controller_manager/src/controller_manager.cpp#L1761) that:

real controller update rate (Hz) = controller_manager.update_rate / controller_name.update_rate

```
  controller_manager:
    ros__parameters:
      update_rate: 50 # Hz

      tricycle_controller:
        type: tricycle_controller/TricycleController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  joint_state_broadcaster:
    ros__parameters:
      update_rate: 10 # Not the real rate! With this configuration /joint_states is published at 50/10 = 5 Hz
```
